import mongoose, { Document, Schema } from 'mongoose';

export type AuditAction =
  | 'auth.login'
  | 'auth.logout'
  | 'auth.password_changed'
  | 'auth.recovery_requested'
  | 'auth.recovery_approved'
  | 'auth.recovery_rejected'
  | 'auth.temp_password_generated'
  | 'auth.pin_reset'
  | 'auth.passkey_registered'
  | 'auth.passkey_removed'
  | 'auth.login_blocked_maintenance'
  | 'maintenance.scheduled'
  | 'maintenance.schedule_cancelled'
  | 'maintenance.enabled'
  | 'maintenance.disabled'
  | 'school_settings.logo_updated'
  | 'school_settings.attendance_rules_updated'
  | 'school_settings.academic_year_updated'
  | 'school_settings.payroll_config_updated'
  | 'school_settings.behavior_window_updated'
  | 'school_settings.attendance_edit_policy_updated'
  | 'school_settings.report_card_branding_updated'
  | 'payroll.generated'
  | 'payroll.generate_all'
  | 'payroll.marked_paid'
  | 'user.created'
  | 'user.updated'
  | 'user.status_changed'
  | 'user.deleted'
  | 'user.bulk_created_parents'
  | 'comm.created'
  | 'comm.updated'
  | 'comm.completed'
  | 'comm.failed'
  | 'comm.cancelled'
  | 'automation.job_created'
  | 'automation.job_started'
  | 'automation.job_completed'
  | 'automation.job_failed'
  | 'automation.job_cancelled'
  | 'automation.job_retried'
  | 'automation.webhook_received'
  | 'ai.call_initiated'
  | 'ai.call_completed'
  | 'ai.call_failed'
  | 'ai.webhook_received'
  | 'ai.transcript_processed'
  | 'ai.usage_logged'
  | 'student.created'
  | 'student.updated'
  | 'student.status_changed'
  | 'student.deleted'
  | 'student.note_added'
  | 'student.note_updated'
  | 'student.note_deleted'
  | 'student.tags_updated'
  | 'student.change_requested'
  | 'student.change_approved'
  | 'student.change_rejected'
  | 'leave_request.created'
  | 'leave_request.approved'
  | 'leave_request.rejected'
  | 'teacher.created'
  | 'teacher.updated'
  | 'teacher.status_changed'
  | 'teacher.deleted'
  | 'teacher.note_added'
  | 'teacher.note_updated'
  | 'teacher.note_deleted'
  | 'teacher.linked_user'
  | 'teacher.login_created'
  | 'teacher.login_email_updated'
  | 'teacher.login_deleted'
  | 'teacher.employee_mirror_failed'
  | 'attendance.marked'
  | 'attendance.bulk_marked'
  | 'attendance.updated'
  | 'attendance.deleted'
  | 'behavior.option_created'
  | 'behavior.option_updated'
  | 'behavior.marked'
  | 'behavior.bulk_marked'
  | 'behavior.deleted'
  | 'fee.created'
  | 'fee.updated'
  | 'fee.deleted'
  | 'fee.payment_recorded'
  | 'fee.bulk_payment_recorded'
  | 'fee.receipt_emailed'
  | 'fee.defaulters_emailed'
  | 'fee.reminder_sent'
  | 'fee.statement_emailed'
  | 'fee.discount_requested'
  | 'fee.discount_approved'
  | 'fee.discount_rejected'
  | 'salary.created'
  | 'salary.bulk_created'
  | 'salary.updated'
  | 'salary.paid'
  | 'salary.bulk_paid'
  | 'salary.deleted'
  | 'salary.forced_pending'
  | 'salary.security_deposit_collected'
  | 'class_teacher.assigned'
  | 'class_teacher.unassigned'
  | 'expense.created'
  | 'expense.updated'
  | 'expense.approved'
  | 'expense.deleted'
  | 'vendor.created'
  | 'vendor.updated'
  | 'vendor.deleted'
  | 'vendor_bill.created'
  | 'vendor_bill.updated'
  | 'vendor_payment.recorded'
  | 'event.created'
  | 'event.updated'
  | 'event.status_changed'
  | 'event.deleted'
  | 'enquiry.created'
  | 'enquiry.updated'
  | 'enquiry.stage_changed'
  | 'enquiry.converted'
  | 'enquiry.deleted'
  | 'visitor.checked_in'
  | 'visitor.checked_out'
  | 'visitor.deleted'
  | 'visitor.status_waiting'
  | 'visitor.status_approved'
  | 'visitor.status_in_meeting'
  | 'visitor.status_completed'
  | 'visitor.status_cancelled'
  | 'visitor_appointment.booked'
  | 'visitor_appointment.cancelled'
  | 'reception_task.created'
  | 'reception_task.updated'
  | 'reception_task.deleted'
  | 'reception_task.status_open'
  | 'reception_task.status_in_progress'
  | 'reception_task.status_completed'
  | 'reception_task.status_snoozed'
  | 'reception_task.status_cancelled'
  | 'follow_up.created'
  | 'follow_up.completed'
  | 'follow_up.rescheduled'
  | 'follow_up.deleted'
  | 'admission_form.issued'
  | 'admission_form.payment_updated'
  | 'admission_form.submitted'
  | 'admission_form.verified'
  | 'admission_form.rejected'
  | 'admission_form.deleted'
  | 'candidate.created'
  | 'candidate.forwarded'
  | 'candidate.rejected'
  | 'candidate.deleted'
  | 'candidate.final_decision'
  | 'interview.scheduled'
  | 'interview.status_changed'
  | 'interview.feedback_submitted'
  | 'interview.deleted'
  | 'timetable.created'
  | 'timetable.updated'
  | 'timetable.published'
  | 'timetable.archived'
  | 'timetable.deleted'
  | 'timetable.entry_updated'
  | 'timetable.entries_bulk_updated'
  | 'timetable.substitute_assigned'
  | 'timetable.period_created'
  | 'timetable.period_updated'
  | 'timetable.period_deleted'
  | 'teacher_timetable.entries_updated'
  | 'teacher_timetable.published'
  | 'teacher_timetable.updated'
  | 'teacher_timetable.deleted'
  | 'principal.dashboard.viewed'
  | 'principal.briefing_summary.generated'
  | 'report.generated'
  | 'report.saved'
  | 'report.exported'
  | 'report.deleted'
  | 'workflow.created'
  | 'workflow.updated'
  | 'workflow.enabled'
  | 'workflow.disabled'
  | 'workflow.triggered'
  | 'workflow.retried'
  | 'import.uploaded'
  | 'import.validated'
  | 'import.confirmed'
  | 'import.completed'
  | 'import.failed'
  | 'import.cancelled'
  | 'import.rolled_back'
  | 'import.ai_mapping_requested'
  | 'integration.created'
  | 'integration.updated'
  | 'integration.deleted'
  | 'integration.enabled'
  | 'integration.disabled'
  | 'integration.sync_started'
  | 'integration.sync_completed'
  | 'integration.sync_failed'
  | 'integration.test_connection'
  | 'integration.credentials_updated'
  | 'integration.webhook_received'
  | 'apikey.created'
  | 'apikey.rotated'
  | 'apikey.revoked'
  | 'webhook.created'
  | 'webhook.updated'
  | 'webhook.deleted'
  | 'webhook.delivered'
  | 'webhook.failed'
  | 'internal_message.sent'
  | 'internal_message.acknowledged'
  | 'internal_message.template_created'
  | 'internal_message.template_deleted'
  | 'employee.created'
  | 'employee.updated'
  | 'employee.deleted'
  | 'employee.login_created'
  | 'employee.qr_regenerated'
  | 'employee.qr_disabled'
  | 'staff_attendance.checked_in'
  | 'staff_attendance.checked_out'
  | 'staff_attendance.marked_manual'
  | 'exam.created'
  | 'exam.updated'
  | 'exam.status_changed'
  | 'exam.deleted'
  | 'marks.saved'
  | 'marks.bulk_saved'
  | 'marks.submitted'
  | 'marks.approved'
  | 'marks.correction_requested'
  | 'marks.published'
  | 'marks.locked'
  | 'marks.reopened'
  | 'report_card.generated'
  | 'report_card.updated'
  | 'report_card.remark_regenerated'
  | 'report_card.published'
  | 'report_card_template.created'
  | 'report_card_template.updated'
  | 'report_card_template.published'
  | 'report_card_template.unpublished'
  | 'report_card_template.deleted'
  | 'report_card_template.cloned'
  | 'term_report_card.generated'
  | 'term_report_card.updated'
  | 'term_report_card.skills_updated'
  | 'term_report_card.published'
  | 'notification.sent'
  | 'notification.bulk_sent'
  | 'notification.bulk_job_completed'
  | 'notification.retried'
  | 'notification.webhook_received'
  | 'notification.fee_receipt_sent'
  | 'notification.fee_receipt_retried'
  | 'ai_action.previewed'
  | 'ai_action.executed'
  | 'ai_action.failed'
  | 'communication_settings.updated'
  | 'message_template.created'
  | 'message_template.updated'
  | 'message_template.deleted'
  | 'feature_flag.created'
  | 'feature_flag.updated'
  | 'feature_flag.deleted'
  | 'feature_flag.rollback'
  | 'feature_flag.assignment.created'
  | 'feature_flag.assignment.removed'
  | 'feature_flag.tester_flags_updated'
  | 'module_access.restricted'
  | 'module_access.restored';

export interface IAuditLog extends Document {
  userId: string;
  userDisplayName: string;
  action: AuditAction;
  resource: string;
  resourceId: string;
  details?: Record<string, unknown>;
  ip?: string;
  schoolId: string;
  createdAt: Date;
  updatedAt: Date;
}

const auditLogSchema = new Schema<IAuditLog>(
  {
    userId: { type: String, required: true },
    userDisplayName: { type: String, required: true },
    action: { type: String, required: true },
    resource: { type: String, required: true },
    resourceId: { type: String, required: true },
    details: { type: Schema.Types.Mixed },
    ip: { type: String },
    schoolId: { type: String, required: true },
  },
  { timestamps: true, versionKey: false }
);

auditLogSchema.index({ schoolId: 1, createdAt: -1 });
auditLogSchema.index({ schoolId: 1, action: 1, createdAt: -1 });
auditLogSchema.index({ schoolId: 1, userId: 1, createdAt: -1 });
auditLogSchema.index({ resourceId: 1, createdAt: -1 });
// Audit events are logged on virtually every write path across the app with
// no archival job — without a retention limit this collection grows forever,
// degrading index efficiency and backup size as usage scales. 18 months is
// well past any plausible compliance/investigation window for this app.
auditLogSchema.index({ createdAt: 1 }, { expireAfterSeconds: 60 * 60 * 24 * 548 });

export const AuditLog = mongoose.model<IAuditLog>('AuditLog', auditLogSchema);
