import { Router } from 'express';
import healthRouter from './health.route';
import authRouter from '../features/auth/auth.routes';
import userRouter from '../features/users/user.routes';
import studentRouter from '../features/students/student.routes';
import communicationRouter from '../features/communications/communication.routes';
import automationRouter from '../features/automation/automation.routes';
import aiRouter from '../features/ai/ai.routes';
import teacherRouter from '../features/teachers/teacher.routes';
import attendanceRouter from '../features/attendance/attendance.routes';
import feeRouter from '../features/fees/fee.routes';
import eventRouter from '../features/events/event.routes';
import enquiryRouter from '../features/enquiries/enquiry.routes';
import visitorRouter from '../features/visitors/visitor.routes';
import timetableRouter from '../features/timetable/timetable.routes';
import teacherTimetableRouter from '../features/teacher-timetable/teacher-timetable.routes';
import principalRouter from '../features/principal/principal.routes';
import principalAssistantRouter from '../features/principal-assistant/principal-assistant.routes';
import reportsRouter from '../features/reports/reports.routes';
import workflowRouter from '../features/automation/workflow.routes';
import importRouter from '../features/import/import.routes';
import integrationRouter from '../features/integrations/integration.routes';
import teacherWorkspaceRouter from '../features/teacher-workspace/teacher-workspace.routes';
import salaryRouter from '../features/salary/salary.routes';
import expenseRouter from '../features/expenses/expense.routes';
import accountantWorkspaceRouter from '../features/accountant-workspace/accountant-workspace.routes';
import vendorRouter from '../features/vendors/vendor.routes';
import parentWorkspaceRouter from '../features/parent-workspace/parent-workspace.routes';
import notificationRouter from '../features/notifications/notification.routes';
import classTeacherRouter from '../features/classes/class-teacher.routes';
import studentChangeRequestRouter from '../features/student-change-requests/student-change-request.routes';
import leaveRequestRouter from '../features/leave-requests/leave-request.routes';
import schoolSettingsRouter from '../features/school-settings/school-settings.routes';
import schoolClassRouter from '../features/school-classes/school-class.routes';
import feeStructureRouter from '../features/fees/fee-structure.routes';
import collectionScheduleRouter from '../features/fees/collection-schedule.routes';
import internalMessageRouter from '../features/internal-messages/internal-message.routes';
import deviceTokenRouter from '../features/device-tokens/device-token.routes';
import auditRouter from '../features/audit/audit.routes';
import employeeRouter from '../features/employees/employee.routes';
import staffAttendanceRouter from '../features/staff-attendance/staff-attendance.routes';
import payrollRouter from '../features/payroll/payroll.routes';
import examRouter from '../features/exams/exam.routes';
import marksRouter from '../features/marks/marks.routes';
import reportCardRouter from '../features/report-cards/report-card.routes';
import reportCardTemplateRouter from '../features/report-card-templates/report-card-template.routes';
import termReportCardRouter from '../features/term-report-cards/term-report-card.routes';
import behaviorRouter from '../features/behavior/behavior.routes';
import opsRouter from '../features/ops-center/ops.routes';
import performanceTestRouter from '../features/performance-testing/performance-test.routes';
import communicationEngineRouter from '../features/communication/communication-engine.routes';
import questionBankRouter from '../features/question-bank/question-bank.routes';
import teacherPlannerRouter from '../features/teacher-planner/planner.routes';
import academicYearRouter from '../features/academic-year/academic-year.routes';
import academicPlanRouter from '../features/academic-plan/academic-plan.routes';
import worksheetGeneratorRouter from '../features/worksheet-generator/worksheet.routes';
import syllabusTrackerRouter from '../features/syllabus-tracker/syllabus-tracker.routes';
import featureFlagRouter from '../features/feature-flags/feature-flag.routes';
import featureFlagPublicRouter from '../features/feature-flags/feature-flag.public.routes';
import maintenanceRouter from '../features/maintenance/maintenance.routes';
import maintenancePublicRouter from '../features/maintenance/maintenance.public.routes';
import moduleAccessRouter from '../features/module-access/module-restriction.routes';
import moduleAccessPublicRouter from '../features/module-access/module-restriction.public.routes';
import mockTestRouter from '../features/mock-tests/mock-test.routes';
import transportRouter from '../features/transport/transport.routes';
import receptionTaskRouter from '../features/reception-tasks/reception-task.routes';
import followUpRouter from '../features/follow-ups/follow-up.routes';
import admissionFormRouter from '../features/admission-forms/admission-form.routes';
import candidateRouter from '../features/candidates/candidate.routes';
import interviewRouter from '../features/interviews/interview.routes';

const router = Router();

router.use('/health', healthRouter);
router.use('/auth', authRouter);
router.use('/users', userRouter);
router.use('/students', studentRouter);
router.use('/teachers', teacherRouter);
router.use('/attendance', attendanceRouter);
router.use('/fees', feeRouter);
router.use('/events', eventRouter);
router.use('/enquiries', enquiryRouter);
router.use('/visitors', visitorRouter);
router.use('/reception-tasks', receptionTaskRouter);
router.use('/follow-ups', followUpRouter);
router.use('/admission-forms', admissionFormRouter);
router.use('/candidates', candidateRouter);
router.use('/interviews', interviewRouter);
router.use('/timetable', timetableRouter);
router.use('/teacher-timetable', teacherTimetableRouter);
router.use('/principal', principalRouter);
router.use('/principal-assistant', principalAssistantRouter);
router.use('/reports', reportsRouter);
router.use('/communications', communicationRouter);
router.use('/automation', automationRouter);
router.use('/workflows', workflowRouter);
router.use('/import', importRouter);
router.use('/integrations', integrationRouter);
router.use('/ai', aiRouter);
router.use('/teacher-workspace', teacherWorkspaceRouter);
router.use('/salary', salaryRouter);
router.use('/expenses', expenseRouter);
router.use('/accountant-workspace', accountantWorkspaceRouter);
router.use('/vendors', vendorRouter);
router.use('/parent-workspace', parentWorkspaceRouter);
router.use('/notifications', notificationRouter);
router.use('/classes', classTeacherRouter);
router.use('/student-change-requests', studentChangeRequestRouter);
router.use('/leave-requests', leaveRequestRouter);
router.use('/school-settings', schoolSettingsRouter);
router.use('/school-classes', schoolClassRouter);
router.use('/fee-structure', feeStructureRouter);
router.use('/collection-schedule', collectionScheduleRouter);
router.use('/internal-messages', internalMessageRouter);
router.use('/users/me/device-tokens', deviceTokenRouter);
router.use('/audit', auditRouter);
router.use('/employees', employeeRouter);
router.use('/attendance-qr', staffAttendanceRouter);
router.use('/payroll', payrollRouter);
router.use('/exams', examRouter);
router.use('/marks', marksRouter);
router.use('/report-cards', reportCardRouter);
router.use('/report-card-templates', reportCardTemplateRouter);
router.use('/term-report-cards', termReportCardRouter);
router.use('/behavior', behaviorRouter);
router.use('/ops', opsRouter);
router.use('/performance-tests', performanceTestRouter);
router.use('/communication', communicationEngineRouter);
router.use('/question-bank', questionBankRouter);
router.use('/teacher-planner', teacherPlannerRouter);
router.use('/academic-year', academicYearRouter);
router.use('/academic-plan', academicPlanRouter);
router.use('/worksheet-generator', worksheetGeneratorRouter);
router.use('/syllabus-tracker', syllabusTrackerRouter);
router.use('/ops/feature-flags', featureFlagRouter);
router.use('/feature-flags', featureFlagPublicRouter);
router.use('/ops/maintenance', maintenanceRouter);
router.use('/maintenance', maintenancePublicRouter);
router.use('/ops/module-access', moduleAccessRouter);
router.use('/module-access', moduleAccessPublicRouter);
router.use('/mock-tests', mockTestRouter);
router.use('/transport', transportRouter);

export default router;
