import { Router } from 'express';
import healthRouter from './health.route';
import authRouter from '../features/auth/auth.routes';
import userRouter from '../features/users/user.routes';
import studentRouter from '../features/students/student.routes';
import communicationRouter from '../features/communications/communication.routes';
import automationRouter from '../features/automation/automation.routes';
import aiRouter from '../features/ai/ai.routes';
import teacherRouter from '../features/teachers/teacher.routes';
import attendanceRouter from '../features/attendance/attendance.routes';
import feeRouter from '../features/fees/fee.routes';
import eventRouter from '../features/events/event.routes';
import enquiryRouter from '../features/enquiries/enquiry.routes';
import timetableRouter from '../features/timetable/timetable.routes';
import teacherTimetableRouter from '../features/teacher-timetable/teacher-timetable.routes';
import principalRouter from '../features/principal/principal.routes';
import reportsRouter from '../features/reports/reports.routes';
import workflowRouter from '../features/automation/workflow.routes';
import importRouter from '../features/import/import.routes';
import integrationRouter from '../features/integrations/integration.routes';
import teacherWorkspaceRouter from '../features/teacher-workspace/teacher-workspace.routes';
import salaryRouter from '../features/salary/salary.routes';
import expenseRouter from '../features/expenses/expense.routes';
import accountantWorkspaceRouter from '../features/accountant-workspace/accountant-workspace.routes';
import notificationRouter from '../features/notifications/notification.routes';
import classTeacherRouter from '../features/classes/class-teacher.routes';
import studentChangeRequestRouter from '../features/student-change-requests/student-change-request.routes';
import leaveRequestRouter from '../features/leave-requests/leave-request.routes';
import schoolSettingsRouter from '../features/school-settings/school-settings.routes';
import schoolClassRouter from '../features/school-classes/school-class.routes';
import feeStructureRouter from '../features/fees/fee-structure.routes';
import internalMessageRouter from '../features/internal-messages/internal-message.routes';
import deviceTokenRouter from '../features/device-tokens/device-token.routes';

const router = Router();

router.use('/health', healthRouter);
router.use('/auth', authRouter);
router.use('/users', userRouter);
router.use('/students', studentRouter);
router.use('/teachers', teacherRouter);
router.use('/attendance', attendanceRouter);
router.use('/fees', feeRouter);
router.use('/events', eventRouter);
router.use('/enquiries', enquiryRouter);
router.use('/timetable', timetableRouter);
router.use('/teacher-timetable', teacherTimetableRouter);
router.use('/principal', principalRouter);
router.use('/reports', reportsRouter);
router.use('/communications', communicationRouter);
router.use('/automation', automationRouter);
router.use('/workflows', workflowRouter);
router.use('/import', importRouter);
router.use('/integrations', integrationRouter);
router.use('/ai', aiRouter);
router.use('/teacher-workspace', teacherWorkspaceRouter);
router.use('/salary', salaryRouter);
router.use('/expenses', expenseRouter);
router.use('/accountant-workspace', accountantWorkspaceRouter);
router.use('/notifications', notificationRouter);
router.use('/classes', classTeacherRouter);
router.use('/student-change-requests', studentChangeRequestRouter);
router.use('/leave-requests', leaveRequestRouter);
router.use('/school-settings', schoolSettingsRouter);
router.use('/school-classes', schoolClassRouter);
router.use('/fee-structure', feeStructureRouter);
router.use('/internal-messages', internalMessageRouter);
router.use('/users/me/device-tokens', deviceTokenRouter);

export default router;
